### ISSUE TITLE
Wiki: Pfad für MAC einfügen

### ISSUE THREAD

**Issue by a2er** [jrast/HSR-Latex-Package#2]
...sonst sind die Mac'ies überfordert ;-)

Do heds ganz viel:
http://tex.stackexchange.com/questions/2063/how-can-i-manually-install-a-package-on-miktex-windows

**Comment by jrast** [comment]
Leider aber kein Pfad für MAC user...

**Comment by a2er** [comment]
Ou... isch de falsch link gsii: http://tex.stackexchange.com/a/1167

**Comment by jrast** [comment]
Erledigt!
https://github.com/jrast/HSR-Latex-Package/wiki
