### ISSUE TITLE
Permission to take your work

### ISSUE THREAD

**Issue by NaoPross** [jrast/HSR-Latex-Package#3]
Hallo jrast,
I've just found this project through another old repository on HSR-Stud. I've been doing [pretty much the same thing here](https://github.com/NaoPross/HSR-Stud-Style) and I'm planning to move it into the organization.

I'd like not to waste your work and copy it over in my repository (with appropriate credits), but you haven't specified any license here. Hence the issue.

**Comment by jrast** [comment]
Hey NaoPross!

Nice to see someone interested in using my old stuff! Use whatever you like from this repo, leaving somewhere a note about me would be nice!

**Comment by jrast** [comment]
By the way: Pretty impressing what you created in your repo! Looks a lot more professional than my old stuff! Just one little note: I would recommend to use one of the Koma-Script classes for a semseter or bachelor thesis. These classes provide a lot of configuration options out of the box.

**Comment by NaoPross** [comment]
Thanks! I'll mostly take your beamer code since I haven't created one yet. With a little note somewhere since you're the author. :)

> I would recommend to use one of the Koma-Script classes for a semseter or bachelor thesis. These classes provide a lot of configuration options out of the box.

Yep I know about these but for something as simple as a zusammenfassung I think an article is enough. I'll probably use it for my thesis, though that's still a long way down the road. I'm just finishing my first year at the HSR.
